//***************************************************************************
//! @file     si_osd_resource.h
//! @brief    brief    Resource information generated by the SiI9575
//!                    OSD IForm pages
//
// No part of this work may be reproduced, modified, distributed,
// transmitted, transcribed, or translated into any language or computer
// format, in any form or by any means without written permission of
// Silicon Image, Inc., 1140 East Arques Avenue, Sunnyvale, California 94085
//
// Copyright 2011, Silicon Image, Inc.  All rights reserved.
//***************************************************************************

//----------------------------------------------------------------------------
//	WARNING:: THIS IS A COMPUTER GENERATED FILE!!! DO NOT EDIT
//----------------------------------------------------------------------------


#ifdef SII_RESOURCE_ARRAY_PRINT

#define OSD_WINDOW_NUMBER  34


OsdPtrArray = 
{
	0x01,		// Resource Type
	0x00,		// Win Type
	0xa0,		// Resource Size Low
	0x00,		// Resource Size High
	0x03,		// Number of Fonts
	0x22,		// Number of Content Menus
	0x18,		// Content Pointer Low
	0x00,		// Content Pointer High
	0xA0,		// Font Pointer 0
	0x00,		// Font Pointer 1
	0x00,		// Font Pointer 2
	0x00,		// Font Pointer 3
	0xAC,		// Pointer to Content Resource0 0
	0x00,		// Pointer to Content Resource0 1
	0x00,		// Pointer to Content Resource0 2
	0x00,		// Pointer to Content Resource0 3
	0xE8,		// Pointer to Content Resource1 0
	0x03,		// Pointer to Content Resource1 1
	0x00,		// Pointer to Content Resource1 2
	0x00,		// Pointer to Content Resource1 3
	0x24,		// Pointer to Content Resource2 0
	0x07,		// Pointer to Content Resource2 1
	0x00,		// Pointer to Content Resource2 2
	0x00,		// Pointer to Content Resource2 3
	0x60,		// Pointer to Content Resource3 0
	0x0A,		// Pointer to Content Resource3 1
	0x00,		// Pointer to Content Resource3 2
	0x00,		// Pointer to Content Resource3 3
	0x9C,		// Pointer to Content Resource4 0
	0x0D,		// Pointer to Content Resource4 1
	0x00,		// Pointer to Content Resource4 2
	0x00,		// Pointer to Content Resource4 3
	0xD8,		// Pointer to Content Resource5 0
	0x10,		// Pointer to Content Resource5 1
	0x00,		// Pointer to Content Resource5 2
	0x00,		// Pointer to Content Resource5 3
	0x14,		// Pointer to Content Resource6 0
	0x14,		// Pointer to Content Resource6 1
	0x00,		// Pointer to Content Resource6 2
	0x00,		// Pointer to Content Resource6 3
	0x50,		// Pointer to Content Resource7 0
	0x17,		// Pointer to Content Resource7 1
	0x00,		// Pointer to Content Resource7 2
	0x00,		// Pointer to Content Resource7 3
	0x8C,		// Pointer to Content Resource8 0
	0x1A,		// Pointer to Content Resource8 1
	0x00,		// Pointer to Content Resource8 2
	0x00,		// Pointer to Content Resource8 3
	0xC8,		// Pointer to Content Resource9 0
	0x1D,		// Pointer to Content Resource9 1
	0x00,		// Pointer to Content Resource9 2
	0x00,		// Pointer to Content Resource9 3
	0x04,		// Pointer to Content Resource10 0
	0x21,		// Pointer to Content Resource10 1
	0x00,		// Pointer to Content Resource10 2
	0x00,		// Pointer to Content Resource10 3
	0x40,		// Pointer to Content Resource11 0
	0x24,		// Pointer to Content Resource11 1
	0x00,		// Pointer to Content Resource11 2
	0x00,		// Pointer to Content Resource11 3
	0x7C,		// Pointer to Content Resource12 0
	0x27,		// Pointer to Content Resource12 1
	0x00,		// Pointer to Content Resource12 2
	0x00,		// Pointer to Content Resource12 3
	0xB8,		// Pointer to Content Resource13 0
	0x2A,		// Pointer to Content Resource13 1
	0x00,		// Pointer to Content Resource13 2
	0x00,		// Pointer to Content Resource13 3
	0xF4,		// Pointer to Content Resource14 0
	0x2D,		// Pointer to Content Resource14 1
	0x00,		// Pointer to Content Resource14 2
	0x00,		// Pointer to Content Resource14 3
	0x30,		// Pointer to Content Resource15 0
	0x31,		// Pointer to Content Resource15 1
	0x00,		// Pointer to Content Resource15 2
	0x00,		// Pointer to Content Resource15 3
	0x6C,		// Pointer to Content Resource16 0
	0x34,		// Pointer to Content Resource16 1
	0x00,		// Pointer to Content Resource16 2
	0x00,		// Pointer to Content Resource16 3
	0xA8,		// Pointer to Content Resource17 0
	0x37,		// Pointer to Content Resource17 1
	0x00,		// Pointer to Content Resource17 2
	0x00,		// Pointer to Content Resource17 3
	0xE4,		// Pointer to Content Resource18 0
	0x3A,		// Pointer to Content Resource18 1
	0x00,		// Pointer to Content Resource18 2
	0x00,		// Pointer to Content Resource18 3
	0x20,		// Pointer to Content Resource19 0
	0x3E,		// Pointer to Content Resource19 1
	0x00,		// Pointer to Content Resource19 2
	0x00,		// Pointer to Content Resource19 3
	0x5C,		// Pointer to Content Resource20 0
	0x41,		// Pointer to Content Resource20 1
	0x00,		// Pointer to Content Resource20 2
	0x00,		// Pointer to Content Resource20 3
	0x98,		// Pointer to Content Resource21 0
	0x44,		// Pointer to Content Resource21 1
	0x00,		// Pointer to Content Resource21 2
	0x00,		// Pointer to Content Resource21 3
	0xD4,		// Pointer to Content Resource22 0
	0x47,		// Pointer to Content Resource22 1
	0x00,		// Pointer to Content Resource22 2
	0x00,		// Pointer to Content Resource22 3
	0x10,		// Pointer to Content Resource23 0
	0x4B,		// Pointer to Content Resource23 1
	0x00,		// Pointer to Content Resource23 2
	0x00,		// Pointer to Content Resource23 3
	0x4C,		// Pointer to Content Resource24 0
	0x4E,		// Pointer to Content Resource24 1
	0x00,		// Pointer to Content Resource24 2
	0x00,		// Pointer to Content Resource24 3
	0x88,		// Pointer to Content Resource25 0
	0x51,		// Pointer to Content Resource25 1
	0x00,		// Pointer to Content Resource25 2
	0x00,		// Pointer to Content Resource25 3
	0xC4,		// Pointer to Content Resource26 0
	0x54,		// Pointer to Content Resource26 1
	0x00,		// Pointer to Content Resource26 2
	0x00,		// Pointer to Content Resource26 3
	0x00,		// Pointer to Content Resource27 0
	0x58,		// Pointer to Content Resource27 1
	0x00,		// Pointer to Content Resource27 2
	0x00,		// Pointer to Content Resource27 3
	0x3C,		// Pointer to Content Resource28 0
	0x5B,		// Pointer to Content Resource28 1
	0x00,		// Pointer to Content Resource28 2
	0x00,		// Pointer to Content Resource28 3
	0x78,		// Pointer to Content Resource29 0
	0x5E,		// Pointer to Content Resource29 1
	0x00,		// Pointer to Content Resource29 2
	0x00,		// Pointer to Content Resource29 3
	0xB4,		// Pointer to Content Resource30 0
	0x61,		// Pointer to Content Resource30 1
	0x00,		// Pointer to Content Resource30 2
	0x00,		// Pointer to Content Resource30 3
	0xF0,		// Pointer to Content Resource31 0
	0x64,		// Pointer to Content Resource31 1
	0x00,		// Pointer to Content Resource31 2
	0x00,		// Pointer to Content Resource31 3
	0x2C,		// Pointer to Content Resource32 0
	0x68,		// Pointer to Content Resource32 1
	0x00,		// Pointer to Content Resource32 2
	0x00,		// Pointer to Content Resource32 3
	0x68,		// Pointer to Content Resource33 0
	0x6B,		// Pointer to Content Resource33 1
	0x00,		// Pointer to Content Resource33 2
	0x00,		// Pointer to Content Resource33 3
	0xA4,		// Pointer to Font 16 0
	0x6E,		// Pointer to Font 16 1
	0x00,		// Pointer to Font 16 2
	0x00,		// Pointer to Font 16 3
	0xA8,		// Pointer to Font 16 0
	0x92,		// Pointer to Font 16 1
	0x00,		// Pointer to Font 16 2
	0x00,		// Pointer to Font 16 3
	0xAC,		// Pointer to Font 24 0
	0xB6,		// Pointer to Font 24 1
	0x00,		// Pointer to Font 24 2
	0x00,		// Pointer to Font 24 3
};
#endif

#ifdef SII_OSD_MENU_PRINT
OsdStruct_t OsdData[OSD_WINDOW_NUMBER] =
{
	{
		0x03,		// Type
		0x06,		// WinType
		0xB6,		// Size Low
		0x01,		// Size High
		0x01,		// Window ID Low
		0x00,		// Window ID Hi
		0x00,		// Window Status Low
		0x00,		// Window Status High
		0x00,		// Option Low
		0x00,		// Option Hi
		0x8C,		// Horizontal Start Low
		0x00,		// Horizontal Start High
		0x84,		// Vertical Start Low
		0x01,		// Vertical Start High
		0x08,		// Number of Rows.
		0x20,		// Number of Columns 
		0x00,		// Row Divider
		0x01,		// Border Width
		0x00,		// High Lighted Row
		0x00,		// Disabled Rows Low
		0xFF,		// Disabled Rows High
		0x3F,		// Unselected Avail FG Color
		0x00,		// Unselected Avail BG Color
		0x3F,		// HighLight FG Color
		0x00,		// HighLight BG Color
		0x3F,		// Disabled FG Color
		0x00,		// Disabled BG Color
		0x3F,		// Border Color
		0x3F,		// Row Divider Color
		0x98,		// Alpha Blend
		0x00,		// MilSec display Time Low
		0x00,		// MilSec display Time High
		0x01,		// Window Function Id.
		0x00,		// Paramater 1
		0x00,		// paramater 2
		0x00,		// Paramater 3
		0x00,		// Paramater 4
		0x00,		// editMode
		0x80,		// IForm only, Max row Size
		{
			00,00,00,00,00,00,00,00,
			00,00,00,00,00,00,00,00,
		},
		{
			
			SI_UF_EDITBOX,

		}
		{
			{"                                                                                                                                "},
			{"\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72"},
			{"   A B C D E F G H I J K L M                                                                                                    "},
			{"   N O P Q R S T U V W X Y Z                                                                                                    "},
			{"   0 1 2 3 4 5 6 7 8 9 ! @ #                                                                                                    "},
			{"   % & $ ' ( ) * + - : < = >                                                                                                    "},
			{"\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72"},
			{"   \x66 \x67 \x69 \x68 \x64 \x6A \x6E \x6F                                                                                      "},
		},
	},
	{
		0x03,		// Type
		0x06,		// WinType
		0xB6,		// Size Low
		0x01,		// Size High
		0x02,		// Window ID Low
		0x00,		// Window ID Hi
		0x00,		// Window Status Low
		0x00,		// Window Status High
		0x00,		// Option Low
		0x00,		// Option Hi
		0x8C,		// Horizontal Start Low
		0x00,		// Horizontal Start High
		0x84,		// Vertical Start Low
		0x01,		// Vertical Start High
		0x08,		// Number of Rows.
		0x20,		// Number of Columns 
		0x00,		// Row Divider
		0x01,		// Border Width
		0x00,		// High Lighted Row
		0x00,		// Disabled Rows Low
		0xFF,		// Disabled Rows High
		0x3F,		// Unselected Avail FG Color
		0x00,		// Unselected Avail BG Color
		0x3F,		// HighLight FG Color
		0x00,		// HighLight BG Color
		0x3F,		// Disabled FG Color
		0x00,		// Disabled BG Color
		0x3F,		// Border Color
		0x3F,		// Row Divider Color
		0x98,		// Alpha Blend
		0x00,		// MilSec display Time Low
		0x00,		// MilSec display Time High
		0x01,		// Window Function Id.
		0x00,		// Paramater 1
		0x00,		// paramater 2
		0x00,		// Paramater 3
		0x00,		// Paramater 4
		0x00,		// editMode
		0x80,		// IForm only, Max row Size
		{
			00,00,00,00,00,00,00,00,
			00,00,00,00,00,00,00,00,
		},
		{
			
			SI_UF_EDITBOX,

		}
		{
			{"                                                                                                                                "},
			{"\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72"},
			{"   a b c d e f g h i j k l m                                                                                                    "},
			{"   n o p q r s t u v w x y z                                                                                                    "},
			{"   0 1 2 3 4 5 6 7 8 9 ! @ #                                                                                                    "},
			{"   % & $ ' ( ) * + - : < = >                                                                                                    "},
			{"\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72\x72"},
			{"   \x65 \x67 \x69 \x68 \x64 \x6A \x6E \x6F                                                                                      "},
		},
	},
	{
		0x03,		// Type
		0x05,		// WinType
		0x0E,		// Size Low
		0x01,		// Size High
		0x03,		// Window ID Low
		0x00,		// Window ID Hi
		0x00,		// Window Status Low
		0x00,		// Window Status High
		0x02,		// Option Low
		0x00,		// Option Hi
		0x8C,		// Horizontal Start Low
		0x00,		// Horizontal Start High
		0xC4,		// Vertical Start Low
		0x00,		// Vertical Start High
		0x08,		// Number of Rows.
		0x12,		// Number of Columns 
		0x00,		// Row Divider
		0x00,		// Border Width
		0x00,		// High Lighted Row
		0xF0,		// Disabled Rows Low
		0xFF,		// Disabled Rows High
		0x3F,		// Unselected Avail FG Color
		0x00,		// Unselected Avail BG Color
		0x00,		// HighLight FG Color
		0x0F,		// HighLight BG Color
		0x15,		// Disabled FG Color
		0x00,		// Disabled BG Color
		0x3F,		// Border Color
		0x3F,		// Row Divider Color
		0x98,		// Alpha Blend
		0x00,		// MilSec display Time Low
		0x00,		// MilSec display Time High
		0x02,		// Window Function Id.
		0x00,		// Paramater 1
		0x00,		// paramater 2
		0x00,		// Paramater 3
		0x00,		// Paramater 4
		0x00,		// editMode
		0x48,		// IForm only, Max row Size
		{
			05,05,05,05,05,00,00,00,
			00,00,00,00,00,00,00,00,
		},
		{
			
			SI_UF_MAINMENU,

		}
		{
			{" Video Setup                                                            "},
			{" Audio Setup                                                            "},
			{" OSD Demo                                                               "},
			{" Speaker Menu Demo                                                      "},
			{" Clock Setup                                                            "},
			{"                                                                        "},
			{"                                                                        "},
			{"                                                                        "},
		},
	},
	{
		0x03,		// Type
		0x01,		// WinType
		0xF6,		// Size Low
		0x00,		// Size High
		0x04,		// Window ID Low
		0x00,		// Window ID Hi
		0x00,		// Window Status Low
		0x00,		// Window Status High
		0x00,		// Option Low
		0x00,		// Option Hi
		0x8C,		// Horizontal Start Low
		0x00,		// Horizontal Start High
		0x64,		// Vertical Start Low
		0x00,		// Vertical Start High
		0x04,		// Number of Rows.
		0x20,		// Number of Columns 
		0x00,		// Row Divider
		0x00,		// Border Width
		0x00,		// High Lighted Row
		0xF0,		// Disabled Rows Low
		0xFF,		// Disabled Rows High
		0x3F,		// Unselected Avail FG Color
		0x00,		// Unselected Avail BG Color
		0x3F,		// HighLight FG Color
		0x00,		// HighLight BG Color
		0x3F,		// Disabled FG Color
		0x00,		// Disabled BG Color
		0x3F,		// Border Color
		0x3F,		// Row Divider Color
		0x98,		// Alpha Blend
		0x00,		// MilSec display Time Low
		0x00,		// MilSec display Time High
		0x00,		// Window Function Id.
		0x00,		// Paramater 1
		0x00,		// paramater 2
		0x00,		// Paramater 3
		0x00,		// Paramater 4
		0x00,		// editMode
		0x80,		// IForm only, Max row Size
		{
			00,00,00,00,00,00,00,00,
			00,00,00,00,00,00,00,00,
		},
		{
			0,
		}
		{
			{"                          \x7D\x7e\x81\x82\x85\x86                                                                              "},
			{"                          \x7f\x80\x83\x84\x87\x88                                                                              "},
			{"                                                                                                                                "},
			{"\x76\x76\x76\x76\x76\x76\x76\x76\x76\x76\x76\x76\x76\x76\x76\x76\x76\x76\x76\x76\x76\x76\x76\x76\x76\x76\x76\x76\x76\x76\x76\x76"},
		},
	},
	{
		0x03,		// Type
		0x01,		// WinType
		0x26,		// Size Low
		0x01,		// Size High
		0x05,		// Window ID Low
		0x00,		// Window ID Hi
		0x00,		// Window Status Low
		0x00,		// Window Status High
		0x00,		// Option Low
		0x00,		// Option Hi
		0x8C,		// Horizontal Start Low
		0x00,		// Horizontal Start High
		0x84,		// Vertical Start Low
		0x01,		// Vertical Start High
		0x05,		// Number of Rows.
		0x20,		// Number of Columns 
		0x00,		// Row Divider
		0x00,		// Border Width
		0x00,		// High Lighted Row
		0x00,		// Disabled Rows Low
		0x00,		// Disabled Rows High
		0x3F,		// Unselected Avail FG Color
		0x00,		// Unselected Avail BG Color
		0x3F,		// HighLight FG Color
		0x00,		// HighLight BG Color
		0x2A,		// Disabled FG Color
		0x15,		// Disabled BG Color
		0x3F,		// Border Color
		0x3F,		// Row Divider Color
		0x98,		// Alpha Blend
		0x00,		// MilSec display Time Low
		0x00,		// MilSec display Time High
		0x00,		// Window Function Id.
		0x00,		// Paramater 1
		0x00,		// paramater 2
		0x00,		// Paramater 3
		0x00,		// Paramater 4
		0x00,		// editMode
		0x80,		// IForm only, Max row Size
		{
			00,00,00,00,00,00,00,00,
			00,00,00,00,00,00,00,00,
		},
		{
			0,
		}
		{
			{"\x76\x76\x76\x76\x76\x76\x76\x76\x76\x76\x76\x76\x76\x76\x76\x76\x76\x76\x76\x76\x76\x76\x76\x76\x76\x76\x76\x76\x76\x76\x76\x76"},
			{"                                                                                                                                "},
			{"                                                                                                                                "},
			{"                                                                                                                                "},
			{"                                                                                                                                "},
		},
	},
	{
		0x03,		// Type
		0x01,		// WinType
		0xDE,		// Size Low
		0x00,		// Size High
		0x06,		// Window ID Low
		0x00,		// Window ID Hi
		0x00,		// Window Status Low
		0x00,		// Window Status High
		0x00,		// Option Low
		0x00,		// Option Hi
		0xAC,		// Horizontal Start Low
		0x01,		// Horizontal Start High
		0xC4,		// Vertical Start Low
		0x00,		// Vertical Start High
		0x08,		// Number of Rows.
		0x0E,		// Number of Columns 
		0x00,		// Row Divider
		0x00,		// Border Width
		0x00,		// High Lighted Row
		0x00,		// Disabled Rows Low
		0xFF,		// Disabled Rows High
		0x3F,		// Unselected Avail FG Color
		0x00,		// Unselected Avail BG Color
		0x3F,		// HighLight FG Color
		0x00,		// HighLight BG Color
		0x3F,		// Disabled FG Color
		0x00,		// Disabled BG Color
		0x3F,		// Border Color
		0x3F,		// Row Divider Color
		0x98,		// Alpha Blend
		0x00,		// MilSec display Time Low
		0x00,		// MilSec display Time High
		0x03,		// Window Function Id.
		0x00,		// Paramater 1
		0x00,		// paramater 2
		0x00,		// Paramater 3
		0x00,		// Paramater 4
		0x00,		// editMode
		0x38,		// IForm only, Max row Size
		{
			00,00,00,00,00,00,00,00,
			00,00,00,00,00,00,00,00,
		},
		{
			
			SI_UF_BLANKSUBMENU,

		}
		{
			{"                                                        "},
			{"                                                        "},
			{"                                                        "},
			{"                                                        "},
			{"                                                        "},
			{"                                                        "},
			{"                                                        "},
			{"                                                        "},
		},
	},
	{
		0x03,		// Type
		0x05,		// WinType
		0xDE,		// Size Low
		0x00,		// Size High
		0x07,		// Window ID Low
		0x00,		// Window ID Hi
		0x00,		// Window Status Low
		0x00,		// Window Status High
		0x02,		// Option Low
		0x00,		// Option Hi
		0xAC,		// Horizontal Start Low
		0x01,		// Horizontal Start High
		0xC4,		// Vertical Start Low
		0x00,		// Vertical Start High
		0x08,		// Number of Rows.
		0x0E,		// Number of Columns 
		0x00,		// Row Divider
		0x00,		// Border Width
		0x00,		// High Lighted Row
		0xC0,		// Disabled Rows Low
		0xFF,		// Disabled Rows High
		0x3F,		// Unselected Avail FG Color
		0x00,		// Unselected Avail BG Color
		0x00,		// HighLight FG Color
		0x0F,		// HighLight BG Color
		0x15,		// Disabled FG Color
		0x00,		// Disabled BG Color
		0x3F,		// Border Color
		0x3F,		// Row Divider Color
		0x98,		// Alpha Blend
		0x00,		// MilSec display Time Low
		0x00,		// MilSec display Time High
		0x04,		// Window Function Id.
		0x00,		// Paramater 1
		0x00,		// paramater 2
		0x00,		// Paramater 3
		0x00,		// Paramater 4
		0x00,		// editMode
		0x38,		// IForm only, Max row Size
		{
			00,00,00,00,00,00,00,00,
			00,00,00,00,00,00,00,00,
		},
		{
			
			SI_UF_CROSSOVER,

		}
		{
			{"  40HZ                                                  "},
			{"  60HZ                                                  "},
			{"  80HZ                                                  "},
			{"  90HZ                                                  "},
			{"  100HZ                                                 "},
			{"  110HZ                                                 "},
			{"                                                        "},
			{"                                                        "},
		},
	},
	{
		0x03,		// Type
		0x05,		// WinType
		0x0E,		// Size Low
		0x01,		// Size High
		0x08,		// Window ID Low
		0x00,		// Window ID Hi
		0x00,		// Window Status Low
		0x00,		// Window Status High
		0x02,		// Option Low
		0x00,		// Option Hi
		0x8C,		// Horizontal Start Low
		0x00,		// Horizontal Start High
		0xC4,		// Vertical Start Low
		0x00,		// Vertical Start High
		0x08,		// Number of Rows.
		0x12,		// Number of Columns 
		0x00,		// Row Divider
		0x00,		// Border Width
		0x00,		// High Lighted Row
		0xDC,		// Disabled Rows Low
		0xFF,		// Disabled Rows High
		0x3F,		// Unselected Avail FG Color
		0x00,		// Unselected Avail BG Color
		0x00,		// HighLight FG Color
		0x0F,		// HighLight BG Color
		0x15,		// Disabled FG Color
		0x00,		// Disabled BG Color
		0x3F,		// Border Color
		0x3F,		// Row Divider Color
		0x98,		// Alpha Blend
		0x00,		// MilSec display Time Low
		0x00,		// MilSec display Time High
		0x05,		// Window Function Id.
		0x00,		// Paramater 1
		0x00,		// paramater 2
		0x00,		// Paramater 3
		0x00,		// Paramater 4
		0x00,		// editMode
		0x48,		// IForm only, Max row Size
		{
			05,08,05,05,05,06,00,00,
			00,00,00,00,00,00,00,00,
		},
		{
			
			SI_UF_SPEAKERSETUP,

		}
		{
			{" Amp Assign                                                             "},
			{" Speaker Config                                                         "},
			{" Bass Setting                                                           "},
			{" Distance                                                               "},
			{" Channel Level                                                          "},
			{" Crossover Freq.                                                        "},
			{"                                                                        "},
			{"                                                                        "},
		},
	},
	{
		0x03,		// Type
		0x05,		// WinType
		0xDE,		// Size Low
		0x00,		// Size High
		0x09,		// Window ID Low
		0x00,		// Window ID Hi
		0x00,		// Window Status Low
		0x00,		// Window Status High
		0x00,		// Option Low
		0x00,		// Option Hi
		0xAC,		// Horizontal Start Low
		0x01,		// Horizontal Start High
		0xC4,		// Vertical Start Low
		0x00,		// Vertical Start High
		0x08,		// Number of Rows.
		0x0E,		// Number of Columns 
		0x00,		// Row Divider
		0x00,		// Border Width
		0x00,		// High Lighted Row
		0x00,		// Disabled Rows Low
		0xFF,		// Disabled Rows High
		0x3F,		// Unselected Avail FG Color
		0x00,		// Unselected Avail BG Color
		0x3F,		// HighLight FG Color
		0x00,		// HighLight BG Color
		0x0F,		// Disabled FG Color
		0x00,		// Disabled BG Color
		0x0F,		// Border Color
		0x3F,		// Row Divider Color
		0x98,		// Alpha Blend
		0x00,		// MilSec display Time Low
		0x00,		// MilSec display Time High
		0x06,		// Window Function Id.
		0x00,		// Paramater 1
		0x00,		// paramater 2
		0x00,		// Paramater 3
		0x00,		// Paramater 4
		0x00,		// editMode
		0x38,		// IForm only, Max row Size
		{
			00,00,00,00,00,00,00,00,
			00,00,00,00,00,00,00,00,
		},
		{
			
			SI_UF_SPEAKERCONFIG,

		}
		{
			{"                                                        "},
			{"                                                        "},
			{"                                                        "},
			{"                                                        "},
			{"                                                        "},
			{"                                                        "},
			{"                                                        "},
			{"                                                        "},
		},
	},
	{
		0x03,		// Type
		0x05,		// WinType
		0x0E,		// Size Low
		0x01,		// Size High
		0x0A,		// Window ID Low
		0x00,		// Window ID Hi
		0x00,		// Window Status Low
		0x00,		// Window Status High
		0x02,		// Option Low
		0x00,		// Option Hi
		0x8C,		// Horizontal Start Low
		0x00,		// Horizontal Start High
		0xC4,		// Vertical Start Low
		0x00,		// Vertical Start High
		0x08,		// Number of Rows.
		0x12,		// Number of Columns 
		0x00,		// Row Divider
		0x00,		// Border Width
		0x00,		// High Lighted Row
		0xE0,		// Disabled Rows Low
		0xFF,		// Disabled Rows High
		0x3F,		// Unselected Avail FG Color
		0x00,		// Unselected Avail BG Color
		0x00,		// HighLight FG Color
		0x0F,		// HighLight BG Color
		0x15,		// Disabled FG Color
		0x00,		// Disabled BG Color
		0x3F,		// Border Color
		0x3F,		// Row Divider Color
		0x98,		// Alpha Blend
		0x00,		// MilSec display Time Low
		0x00,		// MilSec display Time High
		0x07,		// Window Function Id.
		0x00,		// Paramater 1
		0x00,		// paramater 2
		0x00,		// Paramater 3
		0x00,		// Paramater 4
		0x00,		// editMode
		0x48,		// IForm only, Max row Size
		{
			00,00,00,00,00,00,00,00,
			00,00,00,00,00,00,00,00,
		},
		{
			
			SI_UF_SPEAKERCONFIG_SUB,

		}
		{
			{" Front                                                                  "},
			{" Center                                                                 "},
			{" Subwoofer                                                              "},
			{" Surround                                                               "},
			{" Rear                                                                   "},
			{"                                                                        "},
			{"                                                                        "},
			{"                                                                        "},
		},
	},
	{
		0x04,		// Type
		0x00,		// WinType
		0x42,		// Size Low
		0x00,		// Size High
		0x0B,		// Window ID Low
		0x00,		// Window ID Hi
		0x00,		// Window Status Low
		0x00,		// Window Status High
		0x00,		// Option Low
		0x00,		// Option Hi
		0x00,		// Horizontal Start Low
		0x00,		// Horizontal Start High
		0x00,		// Vertical Start Low
		0x00,		// Vertical Start High
		0x02,		// Number of Rows.
		0x06,		// Number of Columns 
		0x00,		// Row Divider
		0x00,		// Border Width
		0x00,		// High Lighted Row
		0x00,		// Disabled Rows Low
		0x00,		// Disabled Rows High
		0x00,		// Unselected Avail FG Color
		0x00,		// Unselected Avail BG Color
		0x00,		// HighLight FG Color
		0x00,		// HighLight BG Color
		0x00,		// Disabled FG Color
		0x00,		// Disabled BG Color
		0x00,		// Border Color
		0x00,		// Row Divider Color
		0x00,		// Alpha Blend
		0x00,		// MilSec display Time Low
		0x00,		// MilSec display Time High
		0x00,		// Window Function Id.
		0x00,		// Paramater 1
		0x00,		// paramater 2
		0x00,		// Paramater 3
		0x00,		// Paramater 4
		0x00,		// editMode
		0x18,		// IForm only, Max row Size
		{
			00,00,00,00,00,00,00,00,
			00,00,00,00,00,00,00,00,
		},
		{
			0,
		}
		{
			{"\x7d\x7e\x81\x82\x85\x86"},
			{"\x7f\x80\x83\x84\x87\x88"},
		},
	},
	{
		0x04,		// Type
		0x00,		// WinType
		0x38,		// Size Low
		0x00,		// Size High
		0x0C,		// Window ID Low
		0x00,		// Window ID Hi
		0x00,		// Window Status Low
		0x00,		// Window Status High
		0x00,		// Option Low
		0x00,		// Option Hi
		0x00,		// Horizontal Start Low
		0x00,		// Horizontal Start High
		0x00,		// Vertical Start Low
		0x00,		// Vertical Start High
		0x01,		// Number of Rows.
		0x02,		// Number of Columns 
		0x00,		// Row Divider
		0x00,		// Border Width
		0x00,		// High Lighted Row
		0x00,		// Disabled Rows Low
		0x00,		// Disabled Rows High
		0x00,		// Unselected Avail FG Color
		0x00,		// Unselected Avail BG Color
		0x00,		// HighLight FG Color
		0x00,		// HighLight BG Color
		0x00,		// Disabled FG Color
		0x00,		// Disabled BG Color
		0x00,		// Border Color
		0x00,		// Row Divider Color
		0x00,		// Alpha Blend
		0x00,		// MilSec display Time Low
		0x00,		// MilSec display Time High
		0x00,		// Window Function Id.
		0x00,		// Paramater 1
		0x00,		// paramater 2
		0x00,		// Paramater 3
		0x00,		// Paramater 4
		0x00,		// editMode
		0x08,		// IForm only, Max row Size
		{
			00,00,00,00,00,00,00,00,
			00,00,00,00,00,00,00,00,
		},
		{
			0,
		}
		{
			{"\xa6\xa7"},
		},
	},
	{
		0x04,		// Type
		0x00,		// WinType
		0x38,		// Size Low
		0x00,		// Size High
		0x0D,		// Window ID Low
		0x00,		// Window ID Hi
		0x00,		// Window Status Low
		0x00,		// Window Status High
		0x00,		// Option Low
		0x00,		// Option Hi
		0x00,		// Horizontal Start Low
		0x00,		// Horizontal Start High
		0x00,		// Vertical Start Low
		0x00,		// Vertical Start High
		0x01,		// Number of Rows.
		0x02,		// Number of Columns 
		0x00,		// Row Divider
		0x00,		// Border Width
		0x00,		// High Lighted Row
		0x00,		// Disabled Rows Low
		0x00,		// Disabled Rows High
		0x00,		// Unselected Avail FG Color
		0x00,		// Unselected Avail BG Color
		0x00,		// HighLight FG Color
		0x00,		// HighLight BG Color
		0x00,		// Disabled FG Color
		0x00,		// Disabled BG Color
		0x00,		// Border Color
		0x00,		// Row Divider Color
		0x00,		// Alpha Blend
		0x00,		// MilSec display Time Low
		0x00,		// MilSec display Time High
		0x00,		// Window Function Id.
		0x00,		// Paramater 1
		0x00,		// paramater 2
		0x00,		// Paramater 3
		0x00,		// Paramater 4
		0x00,		// editMode
		0x08,		// IForm only, Max row Size
		{
			00,00,00,00,00,00,00,00,
			00,00,00,00,00,00,00,00,
		},
		{
			0,
		}
		{
			{"\xab\xac"},
		},
	},
	{
		0x04,		// Type
		0x00,		// WinType
		0x37,		// Size Low
		0x00,		// Size High
		0x0E,		// Window ID Low
		0x00,		// Window ID Hi
		0x00,		// Window Status Low
		0x00,		// Window Status High
		0x00,		// Option Low
		0x00,		// Option Hi
		0x00,		// Horizontal Start Low
		0x00,		// Horizontal Start High
		0x00,		// Vertical Start Low
		0x00,		// Vertical Start High
		0x01,		// Number of Rows.
		0x01,		// Number of Columns 
		0x00,		// Row Divider
		0x00,		// Border Width
		0x00,		// High Lighted Row
		0x00,		// Disabled Rows Low
		0x00,		// Disabled Rows High
		0x00,		// Unselected Avail FG Color
		0x00,		// Unselected Avail BG Color
		0x00,		// HighLight FG Color
		0x00,		// HighLight BG Color
		0x00,		// Disabled FG Color
		0x00,		// Disabled BG Color
		0x00,		// Border Color
		0x00,		// Row Divider Color
		0x00,		// Alpha Blend
		0x00,		// MilSec display Time Low
		0x00,		// MilSec display Time High
		0x00,		// Window Function Id.
		0x00,		// Paramater 1
		0x00,		// paramater 2
		0x00,		// Paramater 3
		0x00,		// Paramater 4
		0x00,		// editMode
		0x04,		// IForm only, Max row Size
		{
			00,00,00,00,00,00,00,00,
			00,00,00,00,00,00,00,00,
		},
		{
			0,
		}
		{
			{"\xaa"},
		},
	},
	{
		0x04,		// Type
		0x00,		// WinType
		0x3A,		// Size Low
		0x00,		// Size High
		0x0F,		// Window ID Low
		0x00,		// Window ID Hi
		0x00,		// Window Status Low
		0x00,		// Window Status High
		0x00,		// Option Low
		0x00,		// Option Hi
		0x00,		// Horizontal Start Low
		0x00,		// Horizontal Start High
		0x00,		// Vertical Start Low
		0x00,		// Vertical Start High
		0x02,		// Number of Rows.
		0x02,		// Number of Columns 
		0x00,		// Row Divider
		0x00,		// Border Width
		0x00,		// High Lighted Row
		0x00,		// Disabled Rows Low
		0x00,		// Disabled Rows High
		0x00,		// Unselected Avail FG Color
		0x00,		// Unselected Avail BG Color
		0x00,		// HighLight FG Color
		0x00,		// HighLight BG Color
		0x00,		// Disabled FG Color
		0x00,		// Disabled BG Color
		0x00,		// Border Color
		0x00,		// Row Divider Color
		0x00,		// Alpha Blend
		0x00,		// MilSec display Time Low
		0x00,		// MilSec display Time High
		0x00,		// Window Function Id.
		0x00,		// Paramater 1
		0x00,		// paramater 2
		0x00,		// Paramater 3
		0x00,		// Paramater 4
		0x00,		// editMode
		0x08,		// IForm only, Max row Size
		{
			00,00,00,00,00,00,00,00,
			00,00,00,00,00,00,00,00,
		},
		{
			0,
		}
		{
			{"        "},
			{"\xa8\xa9"},
		},
	},
	{
		0x04,		// Type
		0x00,		// WinType
		0x3A,		// Size Low
		0x00,		// Size High
		0x10,		// Window ID Low
		0x00,		// Window ID Hi
		0x00,		// Window Status Low
		0x00,		// Window Status High
		0x00,		// Option Low
		0x00,		// Option Hi
		0x00,		// Horizontal Start Low
		0x00,		// Horizontal Start High
		0x00,		// Vertical Start Low
		0x00,		// Vertical Start High
		0x02,		// Number of Rows.
		0x02,		// Number of Columns 
		0x00,		// Row Divider
		0x00,		// Border Width
		0x00,		// High Lighted Row
		0x00,		// Disabled Rows Low
		0x00,		// Disabled Rows High
		0x00,		// Unselected Avail FG Color
		0x00,		// Unselected Avail BG Color
		0x00,		// HighLight FG Color
		0x00,		// HighLight BG Color
		0x00,		// Disabled FG Color
		0x00,		// Disabled BG Color
		0x00,		// Border Color
		0x00,		// Row Divider Color
		0x00,		// Alpha Blend
		0x00,		// MilSec display Time Low
		0x00,		// MilSec display Time High
		0x00,		// Window Function Id.
		0x00,		// Paramater 1
		0x00,		// paramater 2
		0x00,		// Paramater 3
		0x00,		// Paramater 4
		0x00,		// editMode
		0x08,		// IForm only, Max row Size
		{
			00,00,00,00,00,00,00,00,
			00,00,00,00,00,00,00,00,
		},
		{
			0,
		}
		{
			{"\x9f\xa0"},
			{"\xa1\xa2"},
		},
	},
	{
		0x04,		// Type
		0x00,		// WinType
		0x38,		// Size Low
		0x00,		// Size High
		0x11,		// Window ID Low
		0x00,		// Window ID Hi
		0x00,		// Window Status Low
		0x00,		// Window Status High
		0x00,		// Option Low
		0x00,		// Option Hi
		0x00,		// Horizontal Start Low
		0x00,		// Horizontal Start High
		0x00,		// Vertical Start Low
		0x00,		// Vertical Start High
		0x02,		// Number of Rows.
		0x01,		// Number of Columns 
		0x00,		// Row Divider
		0x00,		// Border Width
		0x00,		// High Lighted Row
		0x00,		// Disabled Rows Low
		0x00,		// Disabled Rows High
		0x00,		// Unselected Avail FG Color
		0x00,		// Unselected Avail BG Color
		0x00,		// HighLight FG Color
		0x00,		// HighLight BG Color
		0x00,		// Disabled FG Color
		0x00,		// Disabled BG Color
		0x00,		// Border Color
		0x00,		// Row Divider Color
		0x00,		// Alpha Blend
		0x00,		// MilSec display Time Low
		0x00,		// MilSec display Time High
		0x00,		// Window Function Id.
		0x00,		// Paramater 1
		0x00,		// paramater 2
		0x00,		// Paramater 3
		0x00,		// Paramater 4
		0x00,		// editMode
		0x04,		// IForm only, Max row Size
		{
			00,00,00,00,00,00,00,00,
			00,00,00,00,00,00,00,00,
		},
		{
			0,
		}
		{
			{"\x99"},
			{"\x9b"},
		},
	},
	{
		0x04,		// Type
		0x00,		// WinType
		0x38,		// Size Low
		0x00,		// Size High
		0x12,		// Window ID Low
		0x00,		// Window ID Hi
		0x00,		// Window Status Low
		0x00,		// Window Status High
		0x00,		// Option Low
		0x00,		// Option Hi
		0x00,		// Horizontal Start Low
		0x00,		// Horizontal Start High
		0x00,		// Vertical Start Low
		0x00,		// Vertical Start High
		0x02,		// Number of Rows.
		0x01,		// Number of Columns 
		0x00,		// Row Divider
		0x00,		// Border Width
		0x00,		// High Lighted Row
		0x00,		// Disabled Rows Low
		0x00,		// Disabled Rows High
		0x00,		// Unselected Avail FG Color
		0x00,		// Unselected Avail BG Color
		0x00,		// HighLight FG Color
		0x00,		// HighLight BG Color
		0x00,		// Disabled FG Color
		0x00,		// Disabled BG Color
		0x00,		// Border Color
		0x00,		// Row Divider Color
		0x00,		// Alpha Blend
		0x00,		// MilSec display Time Low
		0x00,		// MilSec display Time High
		0x00,		// Window Function Id.
		0x00,		// Paramater 1
		0x00,		// paramater 2
		0x00,		// Paramater 3
		0x00,		// Paramater 4
		0x00,		// editMode
		0x04,		// IForm only, Max row Size
		{
			00,00,00,00,00,00,00,00,
			00,00,00,00,00,00,00,00,
		},
		{
			0,
		}
		{
			{"\x99"},
			{"\x9a"},
		},
	},
	{
		0x04,		// Type
		0x00,		// WinType
		0x38,		// Size Low
		0x00,		// Size High
		0x13,		// Window ID Low
		0x00,		// Window ID Hi
		0x00,		// Window Status Low
		0x00,		// Window Status High
		0x00,		// Option Low
		0x00,		// Option Hi
		0x00,		// Horizontal Start Low
		0x00,		// Horizontal Start High
		0x00,		// Vertical Start Low
		0x00,		// Vertical Start High
		0x02,		// Number of Rows.
		0x01,		// Number of Columns 
		0x00,		// Row Divider
		0x00,		// Border Width
		0x00,		// High Lighted Row
		0x00,		// Disabled Rows Low
		0x00,		// Disabled Rows High
		0x00,		// Unselected Avail FG Color
		0x00,		// Unselected Avail BG Color
		0x00,		// HighLight FG Color
		0x00,		// HighLight BG Color
		0x00,		// Disabled FG Color
		0x00,		// Disabled BG Color
		0x00,		// Border Color
		0x00,		// Row Divider Color
		0x00,		// Alpha Blend
		0x00,		// MilSec display Time Low
		0x00,		// MilSec display Time High
		0x00,		// Window Function Id.
		0x00,		// Paramater 1
		0x00,		// paramater 2
		0x00,		// Paramater 3
		0x00,		// Paramater 4
		0x00,		// editMode
		0x04,		// IForm only, Max row Size
		{
			00,00,00,00,00,00,00,00,
			00,00,00,00,00,00,00,00,
		},
		{
			0,
		}
		{
			{"\x9c"},
			{"\x9e"},
		},
	},
	{
		0x04,		// Type
		0x00,		// WinType
		0x38,		// Size Low
		0x00,		// Size High
		0x14,		// Window ID Low
		0x00,		// Window ID Hi
		0x00,		// Window Status Low
		0x00,		// Window Status High
		0x00,		// Option Low
		0x00,		// Option Hi
		0x00,		// Horizontal Start Low
		0x00,		// Horizontal Start High
		0x00,		// Vertical Start Low
		0x00,		// Vertical Start High
		0x02,		// Number of Rows.
		0x01,		// Number of Columns 
		0x00,		// Row Divider
		0x00,		// Border Width
		0x00,		// High Lighted Row
		0x00,		// Disabled Rows Low
		0x00,		// Disabled Rows High
		0x00,		// Unselected Avail FG Color
		0x00,		// Unselected Avail BG Color
		0x00,		// HighLight FG Color
		0x00,		// HighLight BG Color
		0x00,		// Disabled FG Color
		0x00,		// Disabled BG Color
		0x00,		// Border Color
		0x00,		// Row Divider Color
		0x00,		// Alpha Blend
		0x00,		// MilSec display Time Low
		0x00,		// MilSec display Time High
		0x00,		// Window Function Id.
		0x00,		// Paramater 1
		0x00,		// paramater 2
		0x00,		// Paramater 3
		0x00,		// Paramater 4
		0x00,		// editMode
		0x04,		// IForm only, Max row Size
		{
			00,00,00,00,00,00,00,00,
			00,00,00,00,00,00,00,00,
		},
		{
			0,
		}
		{
			{"\x9c"},
			{"\x9d"},
		},
	},
	{
		0x04,		// Type
		0x00,		// WinType
		0x38,		// Size Low
		0x00,		// Size High
		0x15,		// Window ID Low
		0x00,		// Window ID Hi
		0x00,		// Window Status Low
		0x00,		// Window Status High
		0x00,		// Option Low
		0x00,		// Option Hi
		0x00,		// Horizontal Start Low
		0x00,		// Horizontal Start High
		0x00,		// Vertical Start Low
		0x00,		// Vertical Start High
		0x02,		// Number of Rows.
		0x01,		// Number of Columns 
		0x00,		// Row Divider
		0x00,		// Border Width
		0x00,		// High Lighted Row
		0x00,		// Disabled Rows Low
		0x00,		// Disabled Rows High
		0x00,		// Unselected Avail FG Color
		0x00,		// Unselected Avail BG Color
		0x00,		// HighLight FG Color
		0x00,		// HighLight BG Color
		0x00,		// Disabled FG Color
		0x00,		// Disabled BG Color
		0x00,		// Border Color
		0x00,		// Row Divider Color
		0x00,		// Alpha Blend
		0x00,		// MilSec display Time Low
		0x00,		// MilSec display Time High
		0x00,		// Window Function Id.
		0x00,		// Paramater 1
		0x00,		// paramater 2
		0x00,		// Paramater 3
		0x00,		// Paramater 4
		0x00,		// editMode
		0x04,		// IForm only, Max row Size
		{
			00,00,00,00,00,00,00,00,
			00,00,00,00,00,00,00,00,
		},
		{
			0,
		}
		{
			{"\xa3"},
			{"\xa5"},
		},
	},
	{
		0x04,		// Type
		0x00,		// WinType
		0x38,		// Size Low
		0x00,		// Size High
		0x16,		// Window ID Low
		0x00,		// Window ID Hi
		0x00,		// Window Status Low
		0x00,		// Window Status High
		0x00,		// Option Low
		0x00,		// Option Hi
		0x00,		// Horizontal Start Low
		0x00,		// Horizontal Start High
		0x00,		// Vertical Start Low
		0x00,		// Vertical Start High
		0x02,		// Number of Rows.
		0x01,		// Number of Columns 
		0x00,		// Row Divider
		0x00,		// Border Width
		0x00,		// High Lighted Row
		0x00,		// Disabled Rows Low
		0x00,		// Disabled Rows High
		0x00,		// Unselected Avail FG Color
		0x00,		// Unselected Avail BG Color
		0x00,		// HighLight FG Color
		0x00,		// HighLight BG Color
		0x00,		// Disabled FG Color
		0x00,		// Disabled BG Color
		0x00,		// Border Color
		0x00,		// Row Divider Color
		0x00,		// Alpha Blend
		0x00,		// MilSec display Time Low
		0x00,		// MilSec display Time High
		0x00,		// Window Function Id.
		0x00,		// Paramater 1
		0x00,		// paramater 2
		0x00,		// Paramater 3
		0x00,		// Paramater 4
		0x00,		// editMode
		0x04,		// IForm only, Max row Size
		{
			00,00,00,00,00,00,00,00,
			00,00,00,00,00,00,00,00,
		},
		{
			0,
		}
		{
			{"\xa3"},
			{"\xa4"},
		},
	},
	{
		0x03,		// Type
		0x05,		// WinType
		0x0E,		// Size Low
		0x01,		// Size High
		0x17,		// Window ID Low
		0x00,		// Window ID Hi
		0x00,		// Window Status Low
		0x00,		// Window Status High
		0x02,		// Option Low
		0x00,		// Option Hi
		0x8C,		// Horizontal Start Low
		0x00,		// Horizontal Start High
		0xC4,		// Vertical Start Low
		0x00,		// Vertical Start High
		0x08,		// Number of Rows.
		0x12,		// Number of Columns 
		0x00,		// Row Divider
		0x00,		// Border Width
		0x00,		// High Lighted Row
		0xF8,		// Disabled Rows Low
		0xFF,		// Disabled Rows High
		0x3F,		// Unselected Avail FG Color
		0x00,		// Unselected Avail BG Color
		0x00,		// HighLight FG Color
		0x0F,		// HighLight BG Color
		0x15,		// Disabled FG Color
		0x00,		// Disabled BG Color
		0x3F,		// Border Color
		0x3F,		// Row Divider Color
		0x98,		// Alpha Blend
		0x00,		// MilSec display Time Low
		0x00,		// MilSec display Time High
		0x08,		// Window Function Id.
		0x00,		// Paramater 1
		0x00,		// paramater 2
		0x00,		// Paramater 3
		0x00,		// Paramater 4
		0x00,		// editMode
		0x48,		// IForm only, Max row Size
		{
			00,00,00,00,00,00,00,00,
			00,00,00,00,00,00,00,00,
		},
		{
			
			SI_UF_VIDEOSETUP,

		}
		{
			{"  External Video                                                        "},
			{"  Internal Video                                                        "},
			{"  Video Pattern                                                         "},
			{"  Fake video                                                            "},
			{"                                                                        "},
			{"                                                                        "},
			{"                                                                        "},
			{"                                                                        "},
		},
	},
	{
		0x03,		// Type
		0x05,		// WinType
		0xDE,		// Size Low
		0x00,		// Size High
		0x18,		// Window ID Low
		0x00,		// Window ID Hi
		0x00,		// Window Status Low
		0x00,		// Window Status High
		0x02,		// Option Low
		0x00,		// Option Hi
		0xAC,		// Horizontal Start Low
		0x01,		// Horizontal Start High
		0xC4,		// Vertical Start Low
		0x00,		// Vertical Start High
		0x08,		// Number of Rows.
		0x0E,		// Number of Columns 
		0x00,		// Row Divider
		0x00,		// Border Width
		0x00,		// High Lighted Row
		0xF8,		// Disabled Rows Low
		0xFF,		// Disabled Rows High
		0x3F,		// Unselected Avail FG Color
		0x00,		// Unselected Avail BG Color
		0x00,		// HighLight FG Color
		0x0F,		// HighLight BG Color
		0x15,		// Disabled FG Color
		0x00,		// Disabled BG Color
		0x3F,		// Border Color
		0x3F,		// Row Divider Color
		0x98,		// Alpha Blend
		0x00,		// MilSec display Time Low
		0x00,		// MilSec display Time High
		0x09,		// Window Function Id.
		0x00,		// Paramater 1
		0x00,		// paramater 2
		0x00,		// Paramater 3
		0x00,		// Paramater 4
		0x00,		// editMode
		0x38,		// IForm only, Max row Size
		{
			00,00,00,00,00,00,00,00,
			00,00,00,00,00,00,00,00,
		},
		{
			
			SI_UF_VIDEOSETUP_IV,

		}
		{
			{"  480p60                                                "},
			{"  576p50                                                "},
			{"  720p60                                                "},
			{"                                                        "},
			{"                                                        "},
			{"                                                        "},
			{"                                                        "},
			{"                                                        "},
		},
	},
	{
		0x03,		// Type
		0x02,		// WinType
		0x8B,		// Size Low
		0x00,		// Size High
		0x19,		// Window ID Low
		0x00,		// Window ID Hi
		0x00,		// Window Status Low
		0x00,		// Window Status High
		0x00,		// Option Low
		0x12,		// Option Hi
		0xC8,		// Horizontal Start Low
		0x00,		// Horizontal Start High
		0x2C,		// Vertical Start Low
		0x01,		// Vertical Start High
		0x03,		// Number of Rows.
		0x12,		// Number of Columns 
		0x00,		// Row Divider
		0x01,		// Border Width
		0x00,		// High Lighted Row
		0xF8,		// Disabled Rows Low
		0xFF,		// Disabled Rows High
		0x3F,		// Unselected Avail FG Color
		0x03,		// Unselected Avail BG Color
		0x3F,		// HighLight FG Color
		0x03,		// HighLight BG Color
		0x3F,		// Disabled FG Color
		0x00,		// Disabled BG Color
		0x3F,		// Border Color
		0x3F,		// Row Divider Color
		0x00,		// Alpha Blend
		0x88,		// MilSec display Time Low
		0x13,		// MilSec display Time High
		0x0A,		// Window Function Id.
		0x00,		// Paramater 1
		0x63,		// paramater 2
		0x01,		// Paramater 3
		0x00,		// Paramater 4
		0x00,		// editMode
		0x48,		// IForm only, Max row Size
		{
			00,00,00,00,00,00,00,00,
			00,00,00,00,00,00,00,00,
		},
		{
			
			SI_UF_VOLUME_CTRL,

		}
		{
			{"Volume                                                                  "},
			{"                                                                        "},
			{"                                                                        "},
		},
	},
	{
		0x03,		// Type
		0x02,		// WinType
		0x8B,		// Size Low
		0x00,		// Size High
		0x1A,		// Window ID Low
		0x00,		// Window ID Hi
		0x00,		// Window Status Low
		0x00,		// Window Status High
		0x10,		// Option Low
		0x14,		// Option Hi
		0x28,		// Horizontal Start Low
		0x00,		// Horizontal Start High
		0x40,		// Vertical Start Low
		0x00,		// Vertical Start High
		0x03,		// Number of Rows.
		0x12,		// Number of Columns 
		0x00,		// Row Divider
		0x01,		// Border Width
		0x00,		// High Lighted Row
		0x00,		// Disabled Rows Low
		0x00,		// Disabled Rows High
		0x3F,		// Unselected Avail FG Color
		0x03,		// Unselected Avail BG Color
		0x3F,		// HighLight FG Color
		0x03,		// HighLight BG Color
		0x3F,		// Disabled FG Color
		0x03,		// Disabled BG Color
		0x3F,		// Border Color
		0x3F,		// Row Divider Color
		0x94,		// Alpha Blend
		0x64,		// MilSec display Time Low
		0x00,		// MilSec display Time High
		0x0B,		// Window Function Id.
		0x00,		// Paramater 1
		0x00,		// paramater 2
		0x00,		// Paramater 3
		0x00,		// Paramater 4
		0x00,		// editMode
		0x48,		// IForm only, Max row Size
		{
			00,00,00,00,00,00,00,00,
			00,00,00,00,00,00,00,00,
		},
		{
			
			SI_UF_PROGRESS_DEMO,

		}
		{
			{"Download Progress                                                       "},
			{"                                                                        "},
			{"                                                                        "},
		},
	},
	{
		0x03,		// Type
		0x04,		// WinType
		0xDB,		// Size Low
		0x00,		// Size High
		0x1B,		// Window ID Low
		0x00,		// Window ID Hi
		0x00,		// Window Status Low
		0x00,		// Window Status High
		0x26,		// Option Low
		0x00,		// Option Hi
		0xC8,		// Horizontal Start Low
		0x00,		// Horizontal Start High
		0x64,		// Vertical Start Low
		0x00,		// Vertical Start High
		0x06,		// Number of Rows.
		0x12,		// Number of Columns 
		0x00,		// Row Divider
		0x01,		// Border Width
		0x00,		// High Lighted Row
		0xC0,		// Disabled Rows Low
		0xFF,		// Disabled Rows High
		0x3F,		// Unselected Avail FG Color
		0x00,		// Unselected Avail BG Color
		0x00,		// HighLight FG Color
		0x0F,		// HighLight BG Color
		0x3F,		// Disabled FG Color
		0x00,		// Disabled BG Color
		0x03,		// Border Color
		0x3F,		// Row Divider Color
		0x98,		// Alpha Blend
		0x00,		// MilSec display Time Low
		0x00,		// MilSec display Time High
		0x0C,		// Window Function Id.
		0x19,		// Paramater 1
		0x00,		// paramater 2
		0x00,		// Paramater 3
		0x00,		// Paramater 4
		0x00,		// editMode
		0x48,		// IForm only, Max row Size
		{
			00,00,00,00,00,00,00,00,
			00,00,00,00,00,00,00,00,
		},
		{
			
			SI_UF_LISTBOX_DEMO,

		}
		{
			{"                                                                        "},
			{"                                                                        "},
			{"                                                                        "},
			{"                                                                        "},
			{"                                                                        "},
			{"                                                                        "},
		},
	},
	{
		0x03,		// Type
		0x05,		// WinType
		0xDE,		// Size Low
		0x00,		// Size High
		0x1C,		// Window ID Low
		0x00,		// Window ID Hi
		0x00,		// Window Status Low
		0x00,		// Window Status High
		0x02,		// Option Low
		0x00,		// Option Hi
		0xAC,		// Horizontal Start Low
		0x01,		// Horizontal Start High
		0xC4,		// Vertical Start Low
		0x00,		// Vertical Start High
		0x08,		// Number of Rows.
		0x0E,		// Number of Columns 
		0x00,		// Row Divider
		0x00,		// Border Width
		0x00,		// High Lighted Row
		0x00,		// Disabled Rows Low
		0x00,		// Disabled Rows High
		0x3F,		// Unselected Avail FG Color
		0x00,		// Unselected Avail BG Color
		0x00,		// HighLight FG Color
		0x0F,		// HighLight BG Color
		0x15,		// Disabled FG Color
		0x00,		// Disabled BG Color
		0x3F,		// Border Color
		0x3F,		// Row Divider Color
		0x98,		// Alpha Blend
		0x00,		// MilSec display Time Low
		0x00,		// MilSec display Time High
		0x0D,		// Window Function Id.
		0x00,		// Paramater 1
		0x00,		// paramater 2
		0x00,		// Paramater 3
		0x00,		// Paramater 4
		0x00,		// editMode
		0x38,		// IForm only, Max row Size
		{
			00,00,00,00,00,00,00,00,
			00,00,00,00,00,00,00,00,
		},
		{
			
			SI_UF_VIDEOSETUP_IV_PATTERN,

		}
		{
			{"  Red                                                   "},
			{"  Green                                                 "},
			{"  Blue                                                  "},
			{"  Black                                                 "},
			{"  White                                                 "},
			{"  Ramp                                                  "},
			{"  Chessboard                                            "},
			{"  Color Bar                                             "},
		},
	},
	{
		0x03,		// Type
		0x05,		// WinType
		0x0E,		// Size Low
		0x01,		// Size High
		0x1D,		// Window ID Low
		0x00,		// Window ID Hi
		0x00,		// Window Status Low
		0x00,		// Window Status High
		0x02,		// Option Low
		0x00,		// Option Hi
		0x8C,		// Horizontal Start Low
		0x00,		// Horizontal Start High
		0xC4,		// Vertical Start Low
		0x00,		// Vertical Start High
		0x08,		// Number of Rows.
		0x12,		// Number of Columns 
		0x00,		// Row Divider
		0x00,		// Border Width
		0x00,		// High Lighted Row
		0x00,		// Disabled Rows Low
		0x00,		// Disabled Rows High
		0x3F,		// Unselected Avail FG Color
		0x00,		// Unselected Avail BG Color
		0x00,		// HighLight FG Color
		0x0F,		// HighLight BG Color
		0x2A,		// Disabled FG Color
		0x00,		// Disabled BG Color
		0x3F,		// Border Color
		0x3F,		// Row Divider Color
		0x98,		// Alpha Blend
		0x00,		// MilSec display Time Low
		0x00,		// MilSec display Time High
		0x0E,		// Window Function Id.
		0x00,		// Paramater 1
		0x00,		// paramater 2
		0x00,		// Paramater 3
		0x00,		// Paramater 4
		0x00,		// editMode
		0x48,		// IForm only, Max row Size
		{
			00,00,00,00,00,00,00,00,
			00,00,00,00,00,00,00,00,
		},
		{
			
			SI_UF_AUDIOSETUP,

		}
		{
			{"  Audio  Insertion                                                      "},
			{"                                                                        "},
			{"  Audio Extraction                                                      "},
			{"                                                                        "},
			{"                                                                        "},
			{"                                                                        "},
			{"                                                                        "},
			{"                                                                        "},
		},
	},
	{
		0x03,		// Type
		0x05,		// WinType
		0x0E,		// Size Low
		0x01,		// Size High
		0x1E,		// Window ID Low
		0x00,		// Window ID Hi
		0x00,		// Window Status Low
		0x00,		// Window Status High
		0x02,		// Option Low
		0x00,		// Option Hi
		0x8C,		// Horizontal Start Low
		0x00,		// Horizontal Start High
		0xC4,		// Vertical Start Low
		0x00,		// Vertical Start High
		0x08,		// Number of Rows.
		0x12,		// Number of Columns 
		0x00,		// Row Divider
		0x00,		// Border Width
		0x00,		// High Lighted Row
		0xC0,		// Disabled Rows Low
		0xFF,		// Disabled Rows High
		0x3F,		// Unselected Avail FG Color
		0x00,		// Unselected Avail BG Color
		0x00,		// HighLight FG Color
		0x0F,		// HighLight BG Color
		0x15,		// Disabled FG Color
		0x00,		// Disabled BG Color
		0x3F,		// Border Color
		0x3F,		// Row Divider Color
		0x98,		// Alpha Blend
		0x00,		// MilSec display Time Low
		0x00,		// MilSec display Time High
		0x0F,		// Window Function Id.
		0x00,		// Paramater 1
		0x00,		// paramater 2
		0x00,		// Paramater 3
		0x00,		// Paramater 4
		0x00,		// editMode
		0x48,		// IForm only, Max row Size
		{
			05,05,05,05,05,05,1E,00,
			00,00,00,00,00,00,00,00,
		},
		{
			
			SI_UF_OSDDEMO,

		}
		{
			{" Port Info Window                                                       "},
			{" Message Box                                                            "},
			{" Progress Bar                                                           "},
			{" Volume Control                                                         "},
			{" List Box                                                               "},
			{" Edit Box                                                               "},
			{" Window Attributes                                                      "},
			{"                                                                        "},
		},
	},
	{
		0x03,		// Type
		0x05,		// WinType
		0xDE,		// Size Low
		0x00,		// Size High
		0x1F,		// Window ID Low
		0x00,		// Window ID Hi
		0x00,		// Window Status Low
		0x00,		// Window Status High
		0x00,		// Option Low
		0x00,		// Option Hi
		0xAC,		// Horizontal Start Low
		0x01,		// Horizontal Start High
		0x40,		// Vertical Start Low
		0x00,		// Vertical Start High
		0x08,		// Number of Rows.
		0x0E,		// Number of Columns 
		0x00,		// Row Divider
		0x00,		// Border Width
		0x00,		// High Lighted Row
		0x00,		// Disabled Rows Low
		0x00,		// Disabled Rows High
		0x3F,		// Unselected Avail FG Color
		0x00,		// Unselected Avail BG Color
		0x00,		// HighLight FG Color
		0x0F,		// HighLight BG Color
		0x15,		// Disabled FG Color
		0x00,		// Disabled BG Color
		0x3F,		// Border Color
		0x3F,		// Row Divider Color
		0x98,		// Alpha Blend
		0x00,		// MilSec display Time Low
		0x00,		// MilSec display Time High
		0x10,		// Window Function Id.
		0x00,		// Paramater 1
		0x00,		// paramater 2
		0x00,		// Paramater 3
		0x00,		// Paramater 4
		0x00,		// editMode
		0x38,		// IForm only, Max row Size
		{
			1F,1F,1F,1F,1F,1F,00,00,
			00,00,00,00,00,00,00,00,
		},
		{
			
			SI_UF_OSDATTR,

		}
		{
			{"  Position \x6C\x6D\x6E\x6F                             "},
			{"  Borders                                               "},
			{"  Dividers                                              "},
			{"  Alpha Blend                                           "},
			{"  Colors                                                "},
			{"  Size                                                  "},
			{"                                                        "},
			{"                                                        "},
		},
	},
	{
		0x03,		// Type
		0x01,		// WinType
		0x7E,		// Size Low
		0x00,		// Size High
		0x20,		// Window ID Low
		0x00,		// Window ID Hi
		0x00,		// Window Status Low
		0x00,		// Window Status High
		0x04,		// Option Low
		0x00,		// Option Hi
		0x28,		// Horizontal Start Low
		0x00,		// Horizontal Start High
		0x40,		// Vertical Start Low
		0x00,		// Vertical Start High
		0x02,		// Number of Rows.
		0x18,		// Number of Columns 
		0x00,		// Row Divider
		0x00,		// Border Width
		0x00,		// High Lighted Row
		0xFC,		// Disabled Rows Low
		0xFF,		// Disabled Rows High
		0x3F,		// Unselected Avail FG Color
		0x02,		// Unselected Avail BG Color
		0x3F,		// HighLight FG Color
		0x00,		// HighLight BG Color
		0x3F,		// Disabled FG Color
		0x00,		// Disabled BG Color
		0x3F,		// Border Color
		0x3F,		// Row Divider Color
		0x94,		// Alpha Blend
		0x88,		// MilSec display Time Low
		0x13,		// MilSec display Time High
		0x11,		// Window Function Id.
		0x00,		// Paramater 1
		0x00,		// paramater 2
		0x00,		// Paramater 3
		0x00,		// Paramater 4
		0x00,		// editMode
		0x60,		// IForm only, Max row Size
		{
			00,00,00,00,00,00,00,00,
			00,00,00,00,00,00,00,00,
		},
		{
			
			SI_UF_DEMO_MSGBOX,

		}
		{
			{"   \x6eOSD Demo Message\x6f                                                                     "},
			{"                                                                                                "},
		},
	},
	{
		0x03,		// Type
		0x03,		// WinType
		0xF6,		// Size Low
		0x00,		// Size High
		0x21,		// Window ID Low
		0x00,		// Window ID Hi
		0x00,		// Window Status Low
		0x00,		// Window Status High
		0x00,		// Option Low
		0x00,		// Option Hi
		0x00,		// Horizontal Start Low
		0x00,		// Horizontal Start High
		0x00,		// Vertical Start Low
		0x00,		// Vertical Start High
		0x04,		// Number of Rows.
		0x20,		// Number of Columns 
		0x00,		// Row Divider
		0x00,		// Border Width
		0x00,		// High Lighted Row
		0xF0,		// Disabled Rows Low
		0xFF,		// Disabled Rows High
		0x3F,		// Unselected Avail FG Color
		0x03,		// Unselected Avail BG Color
		0x3F,		// HighLight FG Color
		0x03,		// HighLight BG Color
		0x3F,		// Disabled FG Color
		0x03,		// Disabled BG Color
		0x3F,		// Border Color
		0x3F,		// Row Divider Color
		0x92,		// Alpha Blend
		0x88,		// MilSec display Time Low
		0x13,		// MilSec display Time High
		0x12,		// Window Function Id.
		0x00,		// Paramater 1
		0x00,		// paramater 2
		0x00,		// Paramater 3
		0x00,		// Paramater 4
		0x00,		// editMode
		0x80,		// IForm only, Max row Size
		{
			00,00,00,00,00,00,00,00,
			00,00,00,00,00,00,00,00,
		},
		{
			
			SI_UF_INFO,

		}
		{
			{"                                                                                                                                "},
			{"                                                                                                                                "},
			{"                                                                                                                                "},
			{"                                                                                                                                "},
		},
	},
	{
		0x03,		// Type
		0x05,		// WinType
		0xDE,		// Size Low
		0x00,		// Size High
		0x22,		// Window ID Low
		0x00,		// Window ID Hi
		0x00,		// Window Status Low
		0x00,		// Window Status High
		0x02,		// Option Low
		0x00,		// Option Hi
		0xAC,		// Horizontal Start Low
		0x01,		// Horizontal Start High
		0xC4,		// Vertical Start Low
		0x00,		// Vertical Start High
		0x08,		// Number of Rows.
		0x0E,		// Number of Columns 
		0x00,		// Row Divider
		0x00,		// Border Width
		0x00,		// High Lighted Row
		0x00,		// Disabled Rows Low
		0xFF,		// Disabled Rows High
		0x3F,		// Unselected Avail FG Color
		0x00,		// Unselected Avail BG Color
		0x00,		// HighLight FG Color
		0x0F,		// HighLight BG Color
		0x15,		// Disabled FG Color
		0x00,		// Disabled BG Color
		0x3F,		// Border Color
		0x3F,		// Row Divider Color
		0x98,		// Alpha Blend
		0x00,		// MilSec display Time Low
		0x00,		// MilSec display Time High
		0x13,		// Window Function Id.
		0x00,		// Paramater 1
		0x00,		// paramater 2
		0x00,		// Paramater 3
		0x00,		// Paramater 4
		0x00,		// editMode
		0x38,		// IForm only, Max row Size
		{
			00,00,00,00,00,00,00,00,
			00,00,00,00,00,00,00,00,
		},
		{
			
			SI_UF_AUDIOSETUP_CONTROLS,

		}
		{
			{"                                                        "},
			{"                                                        "},
			{"                                                        "},
			{"                                                        "},
			{"                                                        "},
			{"                                                        "},
			{"                                                        "},
			{"                                                        "},
		},
	},
};

#endif // SII_OSD_MENU_PRINT

#if !defined __IS_OSD_RESOURCE_H__
#define __IS_OSD_RESOURCE_H__

// Resource Enums
typedef enum 
{
	RID_NONE,
	RID0_WINDOW1_SI_UF_EDITBOX,
	RID1_WINDOW2_SI_UF_EDITBOX,
	RID2_WINDOW3_SI_UF_MAINMENU,
	RID3_WINDOW4,
	RID4_WINDOW5,
	RID5_WINDOW6_SI_UF_BLANKSUBMENU,
	RID6_WINDOW7_SI_UF_CROSSOVER,
	RID7_WINDOW8_SI_UF_SPEAKERSETUP,
	RID8_WINDOW9_SI_UF_SPEAKERCONFIG,
	RID9_WINDOW10_SI_UF_SPEAKERCONFIG_SUB,
	RID10_ICON1,
	RID11_ICON2,
	RID12_ICON3,
	RID13_ICON4,
	RID14_ICON5,
	RID15_ICON6,
	RID16_ICON7,
	RID17_ICON8,
	RID18_ICON9,
	RID19_ICON10,
	RID20_ICON11,
	RID21_ICON12,
	RID22_WINDOW11_SI_UF_VIDEOSETUP,
	RID23_WINDOW12_SI_UF_VIDEOSETUP_IV,
	RID24_WINDOW13_SI_UF_VOLUME_CTRL,
	RID25_WINDOW14_SI_UF_PROGRESS_DEMO,
	RID26_WINDOW15_SI_UF_LISTBOX_DEMO,
	RID27_WINDOW16_SI_UF_VIDEOSETUP_IV_PATTERN,
	RID28_WINDOW17_SI_UF_AUDIOSETUP,
	RID29_WINDOW18_SI_UF_OSDDEMO,
	RID30_WINDOW19_SI_UF_OSDATTR,
	RID31_WINDOW20_SI_UF_DEMO_MSGBOX,
	RID32_WINDOW21_SI_UF_INFO,
	RID33_WINDOW22_SI_UF_AUDIOSETUP_CONTROLS,
	RID34_FONT0_16x24,
	RID35_FONT1_12x16,
	RID36_FONT2_24x32,


} SiiResourceId_t;
// Function Enums
typedef enum
{
	SI_UF_NONE,
	SI_UF_EDITBOX,
	SI_UF_MAINMENU,
	SI_UF_BLANKSUBMENU,
	SI_UF_CROSSOVER,
	SI_UF_SPEAKERSETUP,
	SI_UF_SPEAKERCONFIG,
	SI_UF_SPEAKERCONFIG_SUB,
	SI_UF_VIDEOSETUP,
	SI_UF_VIDEOSETUP_IV,
	SI_UF_VOLUME_CTRL,
	SI_UF_PROGRESS_DEMO,
	SI_UF_LISTBOX_DEMO,
	SI_UF_VIDEOSETUP_IV_PATTERN,
	SI_UF_AUDIOSETUP,
	SI_UF_OSDDEMO,
	SI_UF_OSDATTR,
	SI_UF_DEMO_MSGBOX,
	SI_UF_INFO,
	SI_UF_AUDIOSETUP_CONTROLS,
	SI_UF_EXTERNAL_COUNT,

} Sii_UserFunctionId_t;

#endif // __IS_OSD_RESOURCE_H__
