#ifndef __APP_DISPATHCERS_UART_COMMAND_DISPATCHER_H__
#define __APP_DISPATHCERS_UART_COMMAND_DISPATCHER_H__

void UARTCmdDispatcher_CreateTask( void );

#endif /* __APP_DISPATHCERS_UART_COMMAND_DISPATCHER_H__ */

